### ISSUE TITLE
[App] Pouvoir exclure un prénom depuis les résultats de recherche

### ISSUE THREAD

**Issue by girardea** [TheRealCodeKraft/fsearcher-api#5]
L'idée serait de pouvoir exclure des prénoms un peu comme aujourd'hui on a une liste de favoris.

En effet, comme mes stats sont à la maille du département, elles mélangent parfois plusieurs populations et plusieurs modes. Ainsi, si tu cherches un prénom bien parisien bourgeois, ça va aussi te sortir des prénoms arabes, parce que les deux populations habitent le 75.

On pourrait avoir, à côté de chaque prénom dans les résultats, une petite croix rouge pour exclure des prénoms. 

Et du coup il faudrait stocker cette liste (et la remonter vers nos serveurs aussi, pour améliorer les résultats à terme).

**Comment by adrazek** [comment]
Done et déployé !
