### ISSUE TITLE
[App] Relancer une recherche directement depuis les résultats de recherche

### ISSUE THREAD

**Issue by girardea** [TheRealCodeKraft/fsearcher-api#7]
Depuis la page de résultats, on a assez naturellement envie que l'appli se remette à chercher des prénoms qui ressemblent à un des résultats sur lequel on cliquerait. C'est faisable ?

**Comment by girardea** [comment]
Aussi, on "gagnerait un clic" si on pouvait cliquer sur le nom qu'on recherchait, en haut dans la page de résultats, pour écrire ici directement un nouveau prénom. Sans avoir du coup à retourner sur le page d'accueil pour continuer sa recherche.

**Comment by adrazek** [comment]
Done et déployé !

**Comment by girardea** [comment]
Yeah!!!
